### ISSUE TITLE
cowfe -I parameter does not accept a directory path not ending in /

### ISSUE THREAD

**Issue by retrac0** [davidgiven/cowgol#112]
This may not really be a bug, but it perplexed me for a couple minutes.

    bin/cowfe-6502.nncgen.exe  -Irt/ -Irt/bbct/ examples/helloworld.cow helloworld.cob

runs fine.  But:

    bin/cowfe-6502.nncgen.exe  -Irt/ -Irt/bbct examples/helloworld.cow helloworld.cob

does not.

**Comment by davidgiven** [comment]
That's actually intentional --- it's to prevent the compiler from needing to know what the directory separator is. (Unix uses `/`, DOS uses '\', CP/M doesn't use anything...) It should be documented, somewhere.
