### ISSUE TITLE
Hmm, I do not get it at all ... how to use it ... Z80 binary for cpm how ?

### ISSUE THREAD

**Issue by feldti** [davidgiven/cowgol#133]
I don't get it ... how do I create a z80 program (binary) for CP/M ???? What frontend has to be used. I am working under Linux/Ubuntu 22.04. I've compiled all the stuff ...

**Comment by davidgiven** [comment]
You need the generic 16-bit cowfe compiled with ncpmz, and the z80 backend; these are `bin/cowfe-for-16bit-with-ncpmz` and `bin/cowbe-for-z80-with-ncpmz`. The build process will actually put everything together for you and you can find a turnkey CP/M setup in `bin/dist/cpmz` (`bin/dist/cpm` for 8080 code). Just put those files on a CP/M disk and run `demo.sub`.
