### ISSUE TITLE
Links are broken in home README.md

### ISSUE THREAD

**Issue by surferjeff** [davidgiven/cowgol#8]
I clicked the link for "Everything you want to know about Cowgol, the language;" and got a 404.  Specifically, I'd like to know if the language is stack based.  Are parameters passed on the stack?  Does each function get its own stack frame?

**Comment by davidgiven** [comment]
Hmm --- the link works for me...

The language is not stack based at all, and does not use stack frames for anything other than procedure return addresses (all variables are global).

**Comment by davidgiven** [comment]
Ah, you used the links in the github README render. Yes, they're broken there (I have a fix in the works). Try the version at http://cowlark.com/cowgol.

**Comment by davidgiven** [comment]
Should be fixed now.
