### ISSUE TITLE
test.agc missing in agc version repository

### ISSUE THREAD

**Issue by spacex15** [davidgiven/cowgol#9]
title says it all

I sucessfully built and compiled game from source but the test.agc file is missing in repo to assemble it with yaYUL

very cool project

**Comment by davidgiven** [comment]
Er, oops.

**Comment by davidgiven** [comment]
This should, I hope, be fixed now. I even wrote some documentation!

Thanks for the report!

**Comment by spacex15** [comment]
thanks
just a small error in the documentation
it says ./tinycowc lunarlander.agc  to compile instead of ./tinycowc lunarlander.cow

**Comment by davidgiven** [comment]
Bah. Fixed. Thanks.
